package io.effi.rpc.compile;

/**
 * Stores metadata and bytecode for a generated class.
 *
 * @param pkg  the package name
 * @param name the simple class name
 * @param data the generated bytecode
 */
public record GeneratedInfo(String pkg, String name, byte[] data) {}
