package io.effi.rpc.compile;

import io.effi.rpc.util.ClassUtil;

import java.lang.invoke.MethodHandles;
import java.lang.ref.WeakReference;
import java.security.ProtectionDomain;
import java.util.Map;
import java.util.WeakHashMap;
import java.util.concurrent.atomic.AtomicReference;

/**
 * Defines classes dynamically using bytecode at runtime.
 * <p>
 * Manages class loading and definition for dynamically generated bytecode,
 * ensuring proper class loader hierarchy and efficient class definition.
 */
public final class RuntimeClassLoader extends ClassLoader {

    private static final Map<ClassLoader, WeakReference<RuntimeClassLoader>> LOADERS = new WeakHashMap<>();

    private static final ClassLoader SELF_CLASS_LOADER = ClassUtil.findClassLoader(RuntimeClassLoader.class);

    private static final AtomicReference<RuntimeClassLoader> SELF = new AtomicReference<>();

    private RuntimeClassLoader(ClassLoader parent) {
        super(parent);
    }

    /**
     * Returns the runtime class loader associated with the supplied type.
     *
     * @param type target type
     * @return runtime class loader bound to the target type's class loader
     */
    public static RuntimeClassLoader get(Class<?> type) {
        ClassLoader cl = ClassUtil.findClassLoader(type);
        // Reuse the framework loader for targets loaded by the framework class loader.
        if (SELF_CLASS_LOADER.equals(cl)) {
            return SELF.updateAndGet(existing -> existing != null ? existing : new RuntimeClassLoader(cl));
        }
        // Weak values let unused runtime loaders be reclaimed.
        synchronized (LOADERS) {
            WeakReference<RuntimeClassLoader> ref = LOADERS.get(cl);
            if (ref != null) {
                RuntimeClassLoader runtimeClassLoader = ref.get();
                if (runtimeClassLoader != null)
                    return runtimeClassLoader;
                else
                    LOADERS.remove(cl);
            }
            RuntimeClassLoader runtimeClassLoader = new RuntimeClassLoader(cl);
            LOADERS.put(cl, new WeakReference<>(runtimeClassLoader));
            return runtimeClassLoader;
        }
    }

    /**
     * Removes the cached runtime class loader for the supplied parent.
     *
     * @param parent parent class loader
     */
    public static void remove(ClassLoader parent) {
        if (SELF_CLASS_LOADER.equals(parent)) {
            SELF.set(null);
        } else {
            synchronized (LOADERS) {
                LOADERS.remove(parent);
            }
        }
    }

    /**
     * Defines class from bytecode in the target type's package when accessible.
     *
     * @param targetType target type whose package owns the generated class
     * @param name generated class name used as fallback
     * @param bytes generated class bytecode
     * @return defined class
     */
    public Class<?> define(Class<?> targetType, String name, byte[] bytes) {
        try {
            MethodHandles.Lookup lookup = MethodHandles.privateLookupIn(targetType, MethodHandles.lookup());
            return lookup.defineClass(bytes);
        } catch (IllegalAccessException | IllegalArgumentException | SecurityException ignored) {
            // Fallback for named modules that do not open the target package.
        }
        ProtectionDomain pd = targetType.getProtectionDomain();
        return defineClass(name, bytes, 0, bytes.length, pd);
    }

}
