package io.effi.rpc.compile;

import io.effi.rpc.util.ClassUtil;

import java.lang.ref.WeakReference;
import java.lang.reflect.Method;
import java.security.ProtectionDomain;
import java.util.Map;
import java.util.WeakHashMap;
import java.util.concurrent.atomic.AtomicReference;

/**
 * Defines classes dynamically using bytecode at runtime.
 * <p>
 * Manages class loading and definition for dynamically generated bytecode,
 * ensuring proper class loader hierarchy and efficient class definition.
 */
public final class RuntimeClassLoader extends ClassLoader {

    private static final Map<ClassLoader, WeakReference<RuntimeClassLoader>> LOADERS = new WeakHashMap<>();

    private static final ClassLoader SELF_CLASS_LOADER = ClassUtil.findClassLoader(RuntimeClassLoader.class);

    private static final AtomicReference<RuntimeClassLoader> SELF = new AtomicReference<>();

    private static volatile Method DEFINE_CLASS_METHOD;

    private RuntimeClassLoader(ClassLoader parent) {
        super(parent);
    }

    /**
     * Gets or creates RuntimeClassLoader bound to given type’s class loader.
     */
    public static RuntimeClassLoader get(Class<?> type) {
        ClassLoader cl = ClassUtil.findClassLoader(type);
        // fast‑path: same parent as this class
        if (SELF_CLASS_LOADER.equals(cl)) {
            return SELF.updateAndGet(existing -> existing != null ? existing : new RuntimeClassLoader(cl));
        }
        // 2. normal search:
        synchronized (LOADERS) {
            WeakReference<RuntimeClassLoader> ref = LOADERS.get(cl);
            if (ref != null) {
                RuntimeClassLoader runtimeClassLoader = ref.get();
                if (runtimeClassLoader != null)
                    return runtimeClassLoader;
                else
                    // the value has been GC-reclaimed, but still not the key (defensive sanity)
                    LOADERS.remove(cl);
            }
            RuntimeClassLoader runtimeClassLoader = new RuntimeClassLoader(cl);
            LOADERS.put(cl, new WeakReference<>(runtimeClassLoader));
            return runtimeClassLoader;
        }
    }

    /**
     * Removes cached RuntimeClassLoader for given parent.
     */
    public static void remove(ClassLoader parent) {
        if (SELF_CLASS_LOADER.equals(parent)) {
            SELF.set(null);
        } else {
            synchronized (LOADERS) {
                LOADERS.remove(parent);
            }
        }
    }

    /**
     * Defines class from bytecode, using parent loader first, then this loader if needed.
     */
    public Class<?> define(String name, byte[] bytes) {
        ProtectionDomain pd = getClass().getProtectionDomain();
        try {
            // First, try defining in parent to get package/protected access
            return (Class<?>) defineClassMethod().invoke(getParent(), name, bytes, 0, bytes.length, pd);
        } catch (Exception ignored) {
            // Fallback: define in this loader
        }
        return defineClass(name, bytes, 0, bytes.length, pd);
    }

    private static Method defineClassMethod() throws Exception {
        Method result = DEFINE_CLASS_METHOD;
        if (result == null) {
            synchronized (LOADERS) {
                if (DEFINE_CLASS_METHOD == null) {
                    DEFINE_CLASS_METHOD = result = ClassLoader.class.getDeclaredMethod("defineClass",
                            String.class, byte[].class, int.class, int.class, ProtectionDomain.class);
                    try {
                        DEFINE_CLASS_METHOD.setAccessible(true);
                    } catch (Exception ignored) {
                    }
                }
            }
        }
        return result;
    }

}
