package io.effi.rpc.processor;

import io.effi.rpc.constant.Constant;

import javax.annotation.processing.ProcessingEnvironment;
import javax.tools.FileObject;
import javax.tools.StandardLocation;
import java.io.IOException;
import java.io.OutputStream;
import java.util.ArrayList;
import java.util.List;
import java.util.Properties;

/**
 * Collects scoped component and generates corresponding class files.
 */
public class ScopedComponentResourceSection extends Helper implements ResourceSection {

    private final List<ScopedComponent> scopedComponents = new ArrayList<>();

    public ScopedComponentResourceSection(ProcessingEnvironment processingEnv) {
        super(processingEnv);
    }

    @Override
    public void write() throws IOException {
        if (scopedComponents.isEmpty()) return;
        Properties properties = new Properties();
        for (ScopedComponent component : scopedComponents) {
            String type = component.type();
            properties.setProperty(type, component.scope() + "," + component.kind());
        }
        FileObject resource = filer().createResource(StandardLocation.CLASS_OUTPUT, "", Constant.COMPONENT_PROPERTIES_PATH);
        try (OutputStream os = resource.openOutputStream()) {
            properties.store(os, "Generated by annotation processor");
        }
    }

    public void add(String type, String scope, String kind) {
        scopedComponents.add(new ScopedComponent(type, scope, kind));
    }

    private record ScopedComponent(String type, String scope, String kind) {}
}
